### PR TITLE
Align with recent changes on Gradle plugin

### PR DESCRIPTION
**Pull request by jprinet**
- Extract CI logic to a utility class
- Read Teamcity data from a generated build configuration file

### CODE REVIEW

**Comment by jprinet** [comment]
> Is this ready to review?

I incorporated some changes from https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/123 which is not yet merged. It would probably be better to agree on this one first.

**Comment by jprinet** [comment]
This is ready for review @runningcode 

Here is a [build scan](https://ge.solutions-team.gradle.com/s/olgbjuormsb5y) from _TC 2022.10.1_

**Comment by runningcode** [comment]
Thanks for breaking this up in to smaller PRs. So that I can best review this, can you outline the planned PRs to align the CCUD Maven Extension with the CCUD Gradle Plugin so that I know where to review and what will be covered in a future PR?

**Comment by jprinet** [comment]
You can review the splitted PRs in this order:
- #97 
- #98 
- #99
- #100

**Pull request closed without merging**
